### PR TITLE
[FEATURE] New calculation of shipping costs

### PR DESCRIPTION
**Pull request by GuillaumeG22**
Shipping costs calculated dynamically according to the weight of the products but also for each selected country

This feature is already use in production for one of my project.

### CODE REVIEW

**Comment by dim00z** [comment]
Nice commit, thank you! I hope Casper is available very soon to check/approve this one. This feature has been requested for a while now.

**Comment by Casper-O** [comment]
Thanks for all your commits.

It will take some time before I can check them but it looks promising...

**Comment by Casper-O** [comment]
I like the idea of the shipping cost is calculated by the system per item. I tested it on a client this morning, but they allow pickup at their warehouse, so now all products are "Free shipping"....

We need a solution for this, before we can approve this PR. Beside of this, it do look great.

**Comment by Casper-O** [comment]
I had some time to look though the PR and have I have some thoughts on it.

We might want to consider is, if the same cart could be used though the whole script, instead of a new one for each products.

I don’t know what would be best for performance? It might not be big difference with maybe 100 items in a store, but what with 5000 items?

**Comment by GuillaumeG22** [comment]
Hi,

For the pickup at the warehouse, we need to add a configuration for exclude a carrier.

In a second step, we will deal with the optimization problem related to the creation of the basket. I do not know what is the best.

**Comment by GuillaumeG22** [comment]
I added a field to exclude a carrier.
What do you think ?

**Comment by Casper-O** [comment]
I did not test it yet, but it seems good

**Comment by Casper-O** [comment]
I had a chance to test it and it works as expected.

Now, I hate to bring this up, but in case you update anything on a excluded carrier, it will be given a new carrier id also...

So we actually needs to hook into actionCarrierUpdate and check if an excluded carrier is updated and then Update our exclude list with the new ID.

I have the code for it in an other module. I will try to see if i have time to add it tonight. After that is done, i think we can release the first version and then we check what is best regarding the reuse/new Cart question.

**Comment by Casper-O** [comment]
I added the actionCarrierUpdate, could you please try my suggestion @GuillaumeG22 ?

**Comment by Casper-O** [comment]
@GuillaumeG22 I tested it on a PS 1.6.1.X and confirmed it worked, i messed a little solving a conflict but it seems be ok now.

Thanks for your contribution! :)

**Comment by GuillaumeG22** [comment]
Hi,

It seems good ! 

Great work

**Pull request merged**
